name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  google_fonts: ^6.1.0 
  dio: ^5.3.3 
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.1
  freezed_annotation: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 
  build_runner: ^2.3.3
  freezed: ^2.3.5
  json_serializable: ^6.6.2 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/logo_white.png"  

flutter:
  uses-material-design: true

  assets:
    - assets/png/    
    - assets/jpg/
